/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InquiryType = { 'booking' : null } |
  { 'general' : null };
export interface Request {
  'country' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'state' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Submission {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
}
export interface Submission__1 {
  'inquiryType' : InquiryType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<Submission__1>>,
  'getAllNewsletterSignups' : ActorMethod<[], Array<Submission>>,
  'getAllShowRequests' : ActorMethod<[], Array<Request>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signupNewsletter' : ActorMethod<[string, string], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, InquiryType],
    undefined
  >,
  'submitShowRequest' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];